language: csharp

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

  include:
    - os: linux
      dotnet: 2.1
      mono: none
    - os: osx
      dotnet: 2.1.301
      mono: none

branches:
  only:
  - master
script:
  - dotnet test -c Release -f netcoreapp2.1 test/Abioc.Tests/Abioc.Tests.csproj
